-- BASIC OPTIONS
require('plugins')
require('options')
require('mappings')
require('pluginoptions')

-- PLUGIN OPTIONS
require('telescopeconfig')
require('statusline')
require('snippets')
require('autocompletion')
require('treesitterconfig')
require('comments')
require('troubleconfig')
require('null-ls-config')
require('gitsigns-config')
require('leapconfig')
require('filemanager')
require('notes')
require('zenmode')
require('tmux-navigator')
require('autopairs')
